name: Continous Integration ♾

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  continous-integration:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }} 📦
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install 🔧
        run:
          npm ci

      - name: Test 🧪
        run:
          npm run test

      - name: ESLint 🧹
        run:
          npm run lint
